server:
  port: 8484

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/

spring:
  data:
    mongodb:
      database: ms-basics
      host: localhost
      port: 27017