server:
  port: 8181

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marlonmacf/microservices-basics-configs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/